# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Znamenskiy Lab | Specification and Function of Neural Circuits
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Specification and Function of Neural Circuits Laboratory at the Francis Crick
  Institute studies how the activity of neurons in the neocortex emerges as the
  product of the structure of their synaptic connections and how gene expression
  program's of cortical neurons guide their wiring.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://znamlab.org" # the base hostname & protocol for your site, e.g. http://example.com
github_username: znamlab

sass:
  sass_dir: _sass

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Giscus comments
# Follow instructions on https://giscus.app/ to setup for your repo to fill out the information below.
giscus:
  repo: znamlab/znamlab.github.io # <your-github-user-name>/<your-github-repo-name>
  repo_id: MDEwOlJlcG9zaXRvcnkzMTY5NzA3NzA= # leave empty or specify your repo_id (see https://giscus.app/)
  category: Comments # name of the category under which discussions will be created
  category_id: DIC_kwDOEuSXEs4Ct-Fa # leave empty or specify your category_id (see https://giscus.app/)
  mapping: title # identify discussions by post title
  strict: 1 # use strict identification mode
  reactions_enabled: 1 # enable (1) or disable (0) emoji reactions
  input_position: bottom # whether to display input form below (bottom) or above (top) the comments
  theme: preferred_color_scheme # name of the color scheme (preferred works well with al-folio light/dark mode)
  emit_metadata: 0
  lang: en
